language: node_js
node_js:
  - "10"
install: yarn --frozen-lockfile
script: yarn test
cache:
  directories:
    - node_modules
    - .eslintcache
env:
  matrix:
    - CI=true TZ=Europe/Paris
notifications:
  email: false
